# define mysql Service
apiVersion: v1            # version of my k8s api
kind: Service             # type of resource we want
metadata:                 # info used to identify object
  name: mysql             # name of my service - must be unique
  labels:                 # use to register detailed info about resource
    app: mysql            # tag info to find more easily a resource
spec:
  type: ClusterIP         # state what type of IP = internal cluster IP here
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: mysql
  selector:               # Allow to identify resources with the same label
    app: mysql

---

# define mysql request for volume storage 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce     # Read & write rights on only one node
  resources:
    requests:
      storage: 1Gi      # define volume size to be requested

---

# define image deployment instructions
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:         # define container
      - name: mysql
        image: mysql
        imagePullPolicy: Never # Image will only be pulled localy
        ports:
        - containerPort: 3306
          name: mysql
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - /tmp/liveness_probe.sh
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:     # define where PV is mounted in container
        - mountPath: /var/lib/mysql
          name: mysql
      volumes:            # define PV linked with PVC
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql