# define mysql Service
apiVersion: v1            # version of my k8s api
kind: Service             # type of resource we want
metadata:                 # info used to identify object
  name: phpmyadmin        # name of my service - must be unique
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared ip"
  labels:                 # use to register detailed info about resource
    app: phpmyadmin       # tag info to find more easily a resource
spec:                     # desired state / tech config
  type: LoadBalancer      # state what type of IP
  ports:
    - name: phpmyadmin
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:               # Allow to identify resources with the same label
    app: phpmyadmin

---

# define image deployment instructions
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:           # define container
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never # Image will only be pulled localy
        ports:
        - containerPort: 5000
          name: phpmyadmin